---
name: ci
'on':
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install test dependencies
        run: python3 -m pip install yamllint prospector

      - name: Lint code
        run: |
          yamllint .
          prospector .


  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install test dependencies
        run: python3 -m pip install pytest

      - name: Run tests
        run: pytest


  build_wheels:
    name: Build wheels
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Build wheels
        run: python3 -m pip wheel --wheel-dir dist .

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  build_container_images:
    name: Build and release conatiner images
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
      - build_wheels
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare variables
        id: prepare
        run: |
          VERSION="$(cat VERSION)"
          IMAGE=${{ github.repository }}
          echo "::set-output name=image::${IMAGE}"
          echo "::set-output name=version::${VERSION}"
          echo "::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          echo "::set-output name=project_url::https://github.com/badpacketsllc/bpq"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build and release images to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: |
            docker.io/${{ steps.prepare.outputs.image }}:latest
            docker.io/${{ steps.prepare.outputs.image }}:${{ steps.prepare.outputs.version }}
          build-args: |
            VERSION=${{ steps.prepare.outputs.version }}
          labels: |
            org.opencontainers.image.created=${{ steps.prepare.outputs.created }}
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.url=${{ steps.prepare.outputs.project_url }}
            org.opencontainers.image.documentation=${{ steps.prepare.outputs.project_url }}
            org.opencontainers.image.version=${{ steps.prepare.outputs.version }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build and release images to Quay
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Containerfile
          registry: quay.io
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ steps.prepare.outputs.version }}
          tags: |
            quay.io/${{ steps.prepare.outputs.image }}:latest
            quay.io/${{ steps.prepare.outputs.image }}:${{ steps.prepare.outputs.version }}
          labels: |
            org.opencontainers.image.created=${{ steps.prepare.outputs.created }}
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.url=${{ steps.prepare.outputs.project_url }}
            org.opencontainers.image.documentation=${{ steps.prepare.outputs.project_url }}
            org.opencontainers.image.version=${{ steps.prepare.outputs.version }}
            org.opencontainers.image.revision=${{ github.sha }}
